name: react-build-deploy-s3
# Run workflow only on push to dev branch
on:
  push:
    branches:
      - main # Edit branch name
jobs:
  deploy:
    name: react-build-deploy-s3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-3
      - name: Deploy to S3 bucket
        run: aws s3 sync ./public/ s3://react-cors-spa-b8loh8qf28 --delete # Edit the dist folder and s3 BucketName you get after deploying the AWS CloudFormation template